/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StakeRouteImport } from './routes/stake'
import { Route as StableRouteImport } from './routes/stable'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokensIndexRouteImport } from './routes/tokens.index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as PiIndexRouteImport } from './routes/pi.index'
import { Route as NftIndexRouteImport } from './routes/nft.index'
import { Route as MerchantsIndexRouteImport } from './routes/merchants.index'
import { Route as WalletAddressRouteImport } from './routes/wallet.$address'
import { Route as TxHashRouteImport } from './routes/tx.$hash'
import { Route as TokensSymbolRouteImport } from './routes/tokens.$symbol'
import { Route as NftSlugRouteImport } from './routes/nft.$slug'
import { Route as MerchantsIdRouteImport } from './routes/merchants.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ProEntryIdRouteImport } from './routes/pro.entry.$id'
import { Route as PiTxHashRouteImport } from './routes/pi.tx.$hash'
import { Route as PiOpKeyRouteImport } from './routes/pi.op.$key'
import { Route as ApiPublicTransactionsRouteImport } from './routes/api/public/transactions'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'
import { Route as ApiPublicWalletAddressRouteImport } from './routes/api/public/wallet.$address'
import { Route as ApiPublicTransactionHashRouteImport } from './routes/api/public/transaction.$hash'
import { Route as ApiPublicTokenSymbolRouteImport } from './routes/api/public/token.$symbol'
import { Route as ApiPublicProStatsRouteImport } from './routes/api/public/pro/stats'
import { Route as ApiPublicProEntriesRouteImport } from './routes/api/public/pro/entries'
import { Route as ApiPublicPiTransactionsRouteImport } from './routes/api/public/pi/transactions'
import { Route as ApiPublicPiPaymentsRouteImport } from './routes/api/public/pi/payments'
import { Route as ApiPublicPiOperationsRouteImport } from './routes/api/public/pi/operations'
import { Route as ApiPublicPiAccountRouteImport } from './routes/api/public/pi/account'
import { Route as ApiPublicNftSlugRouteImport } from './routes/api/public/nft.$slug'
import { Route as ApiPublicNftMarketStatsRouteImport } from './routes/api/public/nft-market/stats'
import { Route as ApiPublicNftMarketListingsRouteImport } from './routes/api/public/nft-market/listings'
import { Route as ApiPublicNftMarketCollectionsRouteImport } from './routes/api/public/nft-market/collections'
import { Route as ApiPublicNftMarketActivityRouteImport } from './routes/api/public/nft-market/activity'
import { Route as ApiPublicMerchantIdRouteImport } from './routes/api/public/merchant.$id'
import { Route as ApiPublicLedgerRecordRouteImport } from './routes/api/public/ledger.record'
import { Route as ApiPublicLedgerBulkRouteImport } from './routes/api/public/ledger.bulk'
import { Route as ApiPublicHooksSyncAllRouteImport } from './routes/api/public/hooks/sync-all'
import { Route as ApiPublicProEntriesIdRouteImport } from './routes/api/public/pro/entries.$id'
import { Route as ApiPublicPiTransactionHashRouteImport } from './routes/api/public/pi/transaction.$hash'
import { Route as ApiPublicPiOperationKeyRouteImport } from './routes/api/public/pi/operation.$key'
import { Route as ApiPublicNftSlugCoverRouteImport } from './routes/api/public/nft.$slug.cover'

const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any)
const StableRoute = StableRouteImport.update({
  id: '/stable',
  path: '/stable',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensIndexRoute = TokensIndexRouteImport.update({
  id: '/tokens/',
  path: '/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => rootRouteImport,
} as any)
const PiIndexRoute = PiIndexRouteImport.update({
  id: '/pi/',
  path: '/pi/',
  getParentRoute: () => rootRouteImport,
} as any)
const NftIndexRoute = NftIndexRouteImport.update({
  id: '/nft/',
  path: '/nft/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsIndexRoute = MerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddressRoute = WalletAddressRouteImport.update({
  id: '/wallet/$address',
  path: '/wallet/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const TxHashRoute = TxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensSymbolRoute = TokensSymbolRouteImport.update({
  id: '/tokens/$symbol',
  path: '/tokens/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const NftSlugRoute = NftSlugRouteImport.update({
  id: '/nft/$slug',
  path: '/nft/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsIdRoute = MerchantsIdRouteImport.update({
  id: '/merchants/$id',
  path: '/merchants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProEntryIdRoute = ProEntryIdRouteImport.update({
  id: '/pro/entry/$id',
  path: '/pro/entry/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PiTxHashRoute = PiTxHashRouteImport.update({
  id: '/pi/tx/$hash',
  path: '/pi/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const PiOpKeyRoute = PiOpKeyRouteImport.update({
  id: '/pi/op/$key',
  path: '/pi/op/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTransactionsRoute = ApiPublicTransactionsRouteImport.update({
  id: '/api/public/transactions',
  path: '/api/public/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWalletAddressRoute = ApiPublicWalletAddressRouteImport.update({
  id: '/api/public/wallet/$address',
  path: '/api/public/wallet/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTransactionHashRoute =
  ApiPublicTransactionHashRouteImport.update({
    id: '/api/public/transaction/$hash',
    path: '/api/public/transaction/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTokenSymbolRoute = ApiPublicTokenSymbolRouteImport.update({
  id: '/api/public/token/$symbol',
  path: '/api/public/token/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProStatsRoute = ApiPublicProStatsRouteImport.update({
  id: '/api/public/pro/stats',
  path: '/api/public/pro/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProEntriesRoute = ApiPublicProEntriesRouteImport.update({
  id: '/api/public/pro/entries',
  path: '/api/public/pro/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiTransactionsRoute = ApiPublicPiTransactionsRouteImport.update({
  id: '/api/public/pi/transactions',
  path: '/api/public/pi/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiPaymentsRoute = ApiPublicPiPaymentsRouteImport.update({
  id: '/api/public/pi/payments',
  path: '/api/public/pi/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiOperationsRoute = ApiPublicPiOperationsRouteImport.update({
  id: '/api/public/pi/operations',
  path: '/api/public/pi/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiAccountRoute = ApiPublicPiAccountRouteImport.update({
  id: '/api/public/pi/account',
  path: '/api/public/pi/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNftSlugRoute = ApiPublicNftSlugRouteImport.update({
  id: '/api/public/nft/$slug',
  path: '/api/public/nft/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNftMarketStatsRoute = ApiPublicNftMarketStatsRouteImport.update({
  id: '/api/public/nft-market/stats',
  path: '/api/public/nft-market/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNftMarketListingsRoute =
  ApiPublicNftMarketListingsRouteImport.update({
    id: '/api/public/nft-market/listings',
    path: '/api/public/nft-market/listings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNftMarketCollectionsRoute =
  ApiPublicNftMarketCollectionsRouteImport.update({
    id: '/api/public/nft-market/collections',
    path: '/api/public/nft-market/collections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNftMarketActivityRoute =
  ApiPublicNftMarketActivityRouteImport.update({
    id: '/api/public/nft-market/activity',
    path: '/api/public/nft-market/activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMerchantIdRoute = ApiPublicMerchantIdRouteImport.update({
  id: '/api/public/merchant/$id',
  path: '/api/public/merchant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLedgerRecordRoute = ApiPublicLedgerRecordRouteImport.update({
  id: '/api/public/ledger/record',
  path: '/api/public/ledger/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLedgerBulkRoute = ApiPublicLedgerBulkRouteImport.update({
  id: '/api/public/ledger/bulk',
  path: '/api/public/ledger/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncAllRoute = ApiPublicHooksSyncAllRouteImport.update({
  id: '/api/public/hooks/sync-all',
  path: '/api/public/hooks/sync-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProEntriesIdRoute = ApiPublicProEntriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicProEntriesRoute,
} as any)
const ApiPublicPiTransactionHashRoute =
  ApiPublicPiTransactionHashRouteImport.update({
    id: '/api/public/pi/transaction/$hash',
    path: '/api/public/pi/transaction/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiOperationKeyRoute = ApiPublicPiOperationKeyRouteImport.update({
  id: '/api/public/pi/operation/$key',
  path: '/api/public/pi/operation/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNftSlugCoverRoute = ApiPublicNftSlugCoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => ApiPublicNftSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/kyc': typeof KycRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stable': typeof StableRoute
  '/stake': typeof StakeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/merchants/$id': typeof MerchantsIdRoute
  '/nft/$slug': typeof NftSlugRoute
  '/tokens/$symbol': typeof TokensSymbolRoute
  '/tx/$hash': typeof TxHashRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/nft/': typeof NftIndexRoute
  '/pi/': typeof PiIndexRoute
  '/pro/': typeof ProIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
  '/pi/op/$key': typeof PiOpKeyRoute
  '/pi/tx/$hash': typeof PiTxHashRoute
  '/pro/entry/$id': typeof ProEntryIdRoute
  '/api/public/hooks/sync-all': typeof ApiPublicHooksSyncAllRoute
  '/api/public/ledger/bulk': typeof ApiPublicLedgerBulkRoute
  '/api/public/ledger/record': typeof ApiPublicLedgerRecordRoute
  '/api/public/merchant/$id': typeof ApiPublicMerchantIdRoute
  '/api/public/nft-market/activity': typeof ApiPublicNftMarketActivityRoute
  '/api/public/nft-market/collections': typeof ApiPublicNftMarketCollectionsRoute
  '/api/public/nft-market/listings': typeof ApiPublicNftMarketListingsRoute
  '/api/public/nft-market/stats': typeof ApiPublicNftMarketStatsRoute
  '/api/public/nft/$slug': typeof ApiPublicNftSlugRouteWithChildren
  '/api/public/pi/account': typeof ApiPublicPiAccountRoute
  '/api/public/pi/operations': typeof ApiPublicPiOperationsRoute
  '/api/public/pi/payments': typeof ApiPublicPiPaymentsRoute
  '/api/public/pi/transactions': typeof ApiPublicPiTransactionsRoute
  '/api/public/pro/entries': typeof ApiPublicProEntriesRouteWithChildren
  '/api/public/pro/stats': typeof ApiPublicProStatsRoute
  '/api/public/token/$symbol': typeof ApiPublicTokenSymbolRoute
  '/api/public/transaction/$hash': typeof ApiPublicTransactionHashRoute
  '/api/public/wallet/$address': typeof ApiPublicWalletAddressRoute
  '/api/public/nft/$slug/cover': typeof ApiPublicNftSlugCoverRoute
  '/api/public/pi/operation/$key': typeof ApiPublicPiOperationKeyRoute
  '/api/public/pi/transaction/$hash': typeof ApiPublicPiTransactionHashRoute
  '/api/public/pro/entries/$id': typeof ApiPublicProEntriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/kyc': typeof KycRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stable': typeof StableRoute
  '/stake': typeof StakeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/merchants/$id': typeof MerchantsIdRoute
  '/nft/$slug': typeof NftSlugRoute
  '/tokens/$symbol': typeof TokensSymbolRoute
  '/tx/$hash': typeof TxHashRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/merchants': typeof MerchantsIndexRoute
  '/nft': typeof NftIndexRoute
  '/pi': typeof PiIndexRoute
  '/pro': typeof ProIndexRoute
  '/tokens': typeof TokensIndexRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
  '/pi/op/$key': typeof PiOpKeyRoute
  '/pi/tx/$hash': typeof PiTxHashRoute
  '/pro/entry/$id': typeof ProEntryIdRoute
  '/api/public/hooks/sync-all': typeof ApiPublicHooksSyncAllRoute
  '/api/public/ledger/bulk': typeof ApiPublicLedgerBulkRoute
  '/api/public/ledger/record': typeof ApiPublicLedgerRecordRoute
  '/api/public/merchant/$id': typeof ApiPublicMerchantIdRoute
  '/api/public/nft-market/activity': typeof ApiPublicNftMarketActivityRoute
  '/api/public/nft-market/collections': typeof ApiPublicNftMarketCollectionsRoute
  '/api/public/nft-market/listings': typeof ApiPublicNftMarketListingsRoute
  '/api/public/nft-market/stats': typeof ApiPublicNftMarketStatsRoute
  '/api/public/nft/$slug': typeof ApiPublicNftSlugRouteWithChildren
  '/api/public/pi/account': typeof ApiPublicPiAccountRoute
  '/api/public/pi/operations': typeof ApiPublicPiOperationsRoute
  '/api/public/pi/payments': typeof ApiPublicPiPaymentsRoute
  '/api/public/pi/transactions': typeof ApiPublicPiTransactionsRoute
  '/api/public/pro/entries': typeof ApiPublicProEntriesRouteWithChildren
  '/api/public/pro/stats': typeof ApiPublicProStatsRoute
  '/api/public/token/$symbol': typeof ApiPublicTokenSymbolRoute
  '/api/public/transaction/$hash': typeof ApiPublicTransactionHashRoute
  '/api/public/wallet/$address': typeof ApiPublicWalletAddressRoute
  '/api/public/nft/$slug/cover': typeof ApiPublicNftSlugCoverRoute
  '/api/public/pi/operation/$key': typeof ApiPublicPiOperationKeyRoute
  '/api/public/pi/transaction/$hash': typeof ApiPublicPiTransactionHashRoute
  '/api/public/pro/entries/$id': typeof ApiPublicProEntriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/kyc': typeof KycRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stable': typeof StableRoute
  '/stake': typeof StakeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/merchants/$id': typeof MerchantsIdRoute
  '/nft/$slug': typeof NftSlugRoute
  '/tokens/$symbol': typeof TokensSymbolRoute
  '/tx/$hash': typeof TxHashRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/nft/': typeof NftIndexRoute
  '/pi/': typeof PiIndexRoute
  '/pro/': typeof ProIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
  '/pi/op/$key': typeof PiOpKeyRoute
  '/pi/tx/$hash': typeof PiTxHashRoute
  '/pro/entry/$id': typeof ProEntryIdRoute
  '/api/public/hooks/sync-all': typeof ApiPublicHooksSyncAllRoute
  '/api/public/ledger/bulk': typeof ApiPublicLedgerBulkRoute
  '/api/public/ledger/record': typeof ApiPublicLedgerRecordRoute
  '/api/public/merchant/$id': typeof ApiPublicMerchantIdRoute
  '/api/public/nft-market/activity': typeof ApiPublicNftMarketActivityRoute
  '/api/public/nft-market/collections': typeof ApiPublicNftMarketCollectionsRoute
  '/api/public/nft-market/listings': typeof ApiPublicNftMarketListingsRoute
  '/api/public/nft-market/stats': typeof ApiPublicNftMarketStatsRoute
  '/api/public/nft/$slug': typeof ApiPublicNftSlugRouteWithChildren
  '/api/public/pi/account': typeof ApiPublicPiAccountRoute
  '/api/public/pi/operations': typeof ApiPublicPiOperationsRoute
  '/api/public/pi/payments': typeof ApiPublicPiPaymentsRoute
  '/api/public/pi/transactions': typeof ApiPublicPiTransactionsRoute
  '/api/public/pro/entries': typeof ApiPublicProEntriesRouteWithChildren
  '/api/public/pro/stats': typeof ApiPublicProStatsRoute
  '/api/public/token/$symbol': typeof ApiPublicTokenSymbolRoute
  '/api/public/transaction/$hash': typeof ApiPublicTransactionHashRoute
  '/api/public/wallet/$address': typeof ApiPublicWalletAddressRoute
  '/api/public/nft/$slug/cover': typeof ApiPublicNftSlugCoverRoute
  '/api/public/pi/operation/$key': typeof ApiPublicPiOperationKeyRoute
  '/api/public/pi/transaction/$hash': typeof ApiPublicPiTransactionHashRoute
  '/api/public/pro/entries/$id': typeof ApiPublicProEntriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/explorer'
    | '/kyc'
    | '/sitemap.xml'
    | '/stable'
    | '/stake'
    | '/admin'
    | '/merchants/$id'
    | '/nft/$slug'
    | '/tokens/$symbol'
    | '/tx/$hash'
    | '/wallet/$address'
    | '/merchants/'
    | '/nft/'
    | '/pi/'
    | '/pro/'
    | '/tokens/'
    | '/api/public/analytics'
    | '/api/public/transactions'
    | '/pi/op/$key'
    | '/pi/tx/$hash'
    | '/pro/entry/$id'
    | '/api/public/hooks/sync-all'
    | '/api/public/ledger/bulk'
    | '/api/public/ledger/record'
    | '/api/public/merchant/$id'
    | '/api/public/nft-market/activity'
    | '/api/public/nft-market/collections'
    | '/api/public/nft-market/listings'
    | '/api/public/nft-market/stats'
    | '/api/public/nft/$slug'
    | '/api/public/pi/account'
    | '/api/public/pi/operations'
    | '/api/public/pi/payments'
    | '/api/public/pi/transactions'
    | '/api/public/pro/entries'
    | '/api/public/pro/stats'
    | '/api/public/token/$symbol'
    | '/api/public/transaction/$hash'
    | '/api/public/wallet/$address'
    | '/api/public/nft/$slug/cover'
    | '/api/public/pi/operation/$key'
    | '/api/public/pi/transaction/$hash'
    | '/api/public/pro/entries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/explorer'
    | '/kyc'
    | '/sitemap.xml'
    | '/stable'
    | '/stake'
    | '/admin'
    | '/merchants/$id'
    | '/nft/$slug'
    | '/tokens/$symbol'
    | '/tx/$hash'
    | '/wallet/$address'
    | '/merchants'
    | '/nft'
    | '/pi'
    | '/pro'
    | '/tokens'
    | '/api/public/analytics'
    | '/api/public/transactions'
    | '/pi/op/$key'
    | '/pi/tx/$hash'
    | '/pro/entry/$id'
    | '/api/public/hooks/sync-all'
    | '/api/public/ledger/bulk'
    | '/api/public/ledger/record'
    | '/api/public/merchant/$id'
    | '/api/public/nft-market/activity'
    | '/api/public/nft-market/collections'
    | '/api/public/nft-market/listings'
    | '/api/public/nft-market/stats'
    | '/api/public/nft/$slug'
    | '/api/public/pi/account'
    | '/api/public/pi/operations'
    | '/api/public/pi/payments'
    | '/api/public/pi/transactions'
    | '/api/public/pro/entries'
    | '/api/public/pro/stats'
    | '/api/public/token/$symbol'
    | '/api/public/transaction/$hash'
    | '/api/public/wallet/$address'
    | '/api/public/nft/$slug/cover'
    | '/api/public/pi/operation/$key'
    | '/api/public/pi/transaction/$hash'
    | '/api/public/pro/entries/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analytics'
    | '/auth'
    | '/explorer'
    | '/kyc'
    | '/sitemap.xml'
    | '/stable'
    | '/stake'
    | '/_authenticated/admin'
    | '/merchants/$id'
    | '/nft/$slug'
    | '/tokens/$symbol'
    | '/tx/$hash'
    | '/wallet/$address'
    | '/merchants/'
    | '/nft/'
    | '/pi/'
    | '/pro/'
    | '/tokens/'
    | '/api/public/analytics'
    | '/api/public/transactions'
    | '/pi/op/$key'
    | '/pi/tx/$hash'
    | '/pro/entry/$id'
    | '/api/public/hooks/sync-all'
    | '/api/public/ledger/bulk'
    | '/api/public/ledger/record'
    | '/api/public/merchant/$id'
    | '/api/public/nft-market/activity'
    | '/api/public/nft-market/collections'
    | '/api/public/nft-market/listings'
    | '/api/public/nft-market/stats'
    | '/api/public/nft/$slug'
    | '/api/public/pi/account'
    | '/api/public/pi/operations'
    | '/api/public/pi/payments'
    | '/api/public/pi/transactions'
    | '/api/public/pro/entries'
    | '/api/public/pro/stats'
    | '/api/public/token/$symbol'
    | '/api/public/transaction/$hash'
    | '/api/public/wallet/$address'
    | '/api/public/nft/$slug/cover'
    | '/api/public/pi/operation/$key'
    | '/api/public/pi/transaction/$hash'
    | '/api/public/pro/entries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ExplorerRoute: typeof ExplorerRoute
  KycRoute: typeof KycRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StableRoute: typeof StableRoute
  StakeRoute: typeof StakeRoute
  MerchantsIdRoute: typeof MerchantsIdRoute
  NftSlugRoute: typeof NftSlugRoute
  TokensSymbolRoute: typeof TokensSymbolRoute
  TxHashRoute: typeof TxHashRoute
  WalletAddressRoute: typeof WalletAddressRoute
  MerchantsIndexRoute: typeof MerchantsIndexRoute
  NftIndexRoute: typeof NftIndexRoute
  PiIndexRoute: typeof PiIndexRoute
  ProIndexRoute: typeof ProIndexRoute
  TokensIndexRoute: typeof TokensIndexRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
  ApiPublicTransactionsRoute: typeof ApiPublicTransactionsRoute
  PiOpKeyRoute: typeof PiOpKeyRoute
  PiTxHashRoute: typeof PiTxHashRoute
  ProEntryIdRoute: typeof ProEntryIdRoute
  ApiPublicHooksSyncAllRoute: typeof ApiPublicHooksSyncAllRoute
  ApiPublicLedgerBulkRoute: typeof ApiPublicLedgerBulkRoute
  ApiPublicLedgerRecordRoute: typeof ApiPublicLedgerRecordRoute
  ApiPublicMerchantIdRoute: typeof ApiPublicMerchantIdRoute
  ApiPublicNftMarketActivityRoute: typeof ApiPublicNftMarketActivityRoute
  ApiPublicNftMarketCollectionsRoute: typeof ApiPublicNftMarketCollectionsRoute
  ApiPublicNftMarketListingsRoute: typeof ApiPublicNftMarketListingsRoute
  ApiPublicNftMarketStatsRoute: typeof ApiPublicNftMarketStatsRoute
  ApiPublicNftSlugRoute: typeof ApiPublicNftSlugRouteWithChildren
  ApiPublicPiAccountRoute: typeof ApiPublicPiAccountRoute
  ApiPublicPiOperationsRoute: typeof ApiPublicPiOperationsRoute
  ApiPublicPiPaymentsRoute: typeof ApiPublicPiPaymentsRoute
  ApiPublicPiTransactionsRoute: typeof ApiPublicPiTransactionsRoute
  ApiPublicProEntriesRoute: typeof ApiPublicProEntriesRouteWithChildren
  ApiPublicProStatsRoute: typeof ApiPublicProStatsRoute
  ApiPublicTokenSymbolRoute: typeof ApiPublicTokenSymbolRoute
  ApiPublicTransactionHashRoute: typeof ApiPublicTransactionHashRoute
  ApiPublicWalletAddressRoute: typeof ApiPublicWalletAddressRoute
  ApiPublicPiOperationKeyRoute: typeof ApiPublicPiOperationKeyRoute
  ApiPublicPiTransactionHashRoute: typeof ApiPublicPiTransactionHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable': {
      id: '/stable'
      path: '/stable'
      fullPath: '/stable'
      preLoaderRoute: typeof StableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/': {
      id: '/tokens/'
      path: '/tokens'
      fullPath: '/tokens/'
      preLoaderRoute: typeof TokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi/': {
      id: '/pi/'
      path: '/pi'
      fullPath: '/pi/'
      preLoaderRoute: typeof PiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/': {
      id: '/nft/'
      path: '/nft'
      fullPath: '/nft/'
      preLoaderRoute: typeof NftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/': {
      id: '/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof MerchantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$address': {
      id: '/wallet/$address'
      path: '/wallet/$address'
      fullPath: '/wallet/$address'
      preLoaderRoute: typeof WalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tx/$hash': {
      id: '/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof TxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$symbol': {
      id: '/tokens/$symbol'
      path: '/tokens/$symbol'
      fullPath: '/tokens/$symbol'
      preLoaderRoute: typeof TokensSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/$slug': {
      id: '/nft/$slug'
      path: '/nft/$slug'
      fullPath: '/nft/$slug'
      preLoaderRoute: typeof NftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$id': {
      id: '/merchants/$id'
      path: '/merchants/$id'
      fullPath: '/merchants/$id'
      preLoaderRoute: typeof MerchantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pro/entry/$id': {
      id: '/pro/entry/$id'
      path: '/pro/entry/$id'
      fullPath: '/pro/entry/$id'
      preLoaderRoute: typeof ProEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi/tx/$hash': {
      id: '/pi/tx/$hash'
      path: '/pi/tx/$hash'
      fullPath: '/pi/tx/$hash'
      preLoaderRoute: typeof PiTxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi/op/$key': {
      id: '/pi/op/$key'
      path: '/pi/op/$key'
      fullPath: '/pi/op/$key'
      preLoaderRoute: typeof PiOpKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transactions': {
      id: '/api/public/transactions'
      path: '/api/public/transactions'
      fullPath: '/api/public/transactions'
      preLoaderRoute: typeof ApiPublicTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wallet/$address': {
      id: '/api/public/wallet/$address'
      path: '/api/public/wallet/$address'
      fullPath: '/api/public/wallet/$address'
      preLoaderRoute: typeof ApiPublicWalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transaction/$hash': {
      id: '/api/public/transaction/$hash'
      path: '/api/public/transaction/$hash'
      fullPath: '/api/public/transaction/$hash'
      preLoaderRoute: typeof ApiPublicTransactionHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/token/$symbol': {
      id: '/api/public/token/$symbol'
      path: '/api/public/token/$symbol'
      fullPath: '/api/public/token/$symbol'
      preLoaderRoute: typeof ApiPublicTokenSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pro/stats': {
      id: '/api/public/pro/stats'
      path: '/api/public/pro/stats'
      fullPath: '/api/public/pro/stats'
      preLoaderRoute: typeof ApiPublicProStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pro/entries': {
      id: '/api/public/pro/entries'
      path: '/api/public/pro/entries'
      fullPath: '/api/public/pro/entries'
      preLoaderRoute: typeof ApiPublicProEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/transactions': {
      id: '/api/public/pi/transactions'
      path: '/api/public/pi/transactions'
      fullPath: '/api/public/pi/transactions'
      preLoaderRoute: typeof ApiPublicPiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/payments': {
      id: '/api/public/pi/payments'
      path: '/api/public/pi/payments'
      fullPath: '/api/public/pi/payments'
      preLoaderRoute: typeof ApiPublicPiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/operations': {
      id: '/api/public/pi/operations'
      path: '/api/public/pi/operations'
      fullPath: '/api/public/pi/operations'
      preLoaderRoute: typeof ApiPublicPiOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/account': {
      id: '/api/public/pi/account'
      path: '/api/public/pi/account'
      fullPath: '/api/public/pi/account'
      preLoaderRoute: typeof ApiPublicPiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft/$slug': {
      id: '/api/public/nft/$slug'
      path: '/api/public/nft/$slug'
      fullPath: '/api/public/nft/$slug'
      preLoaderRoute: typeof ApiPublicNftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft-market/stats': {
      id: '/api/public/nft-market/stats'
      path: '/api/public/nft-market/stats'
      fullPath: '/api/public/nft-market/stats'
      preLoaderRoute: typeof ApiPublicNftMarketStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft-market/listings': {
      id: '/api/public/nft-market/listings'
      path: '/api/public/nft-market/listings'
      fullPath: '/api/public/nft-market/listings'
      preLoaderRoute: typeof ApiPublicNftMarketListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft-market/collections': {
      id: '/api/public/nft-market/collections'
      path: '/api/public/nft-market/collections'
      fullPath: '/api/public/nft-market/collections'
      preLoaderRoute: typeof ApiPublicNftMarketCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft-market/activity': {
      id: '/api/public/nft-market/activity'
      path: '/api/public/nft-market/activity'
      fullPath: '/api/public/nft-market/activity'
      preLoaderRoute: typeof ApiPublicNftMarketActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/merchant/$id': {
      id: '/api/public/merchant/$id'
      path: '/api/public/merchant/$id'
      fullPath: '/api/public/merchant/$id'
      preLoaderRoute: typeof ApiPublicMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ledger/record': {
      id: '/api/public/ledger/record'
      path: '/api/public/ledger/record'
      fullPath: '/api/public/ledger/record'
      preLoaderRoute: typeof ApiPublicLedgerRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ledger/bulk': {
      id: '/api/public/ledger/bulk'
      path: '/api/public/ledger/bulk'
      fullPath: '/api/public/ledger/bulk'
      preLoaderRoute: typeof ApiPublicLedgerBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-all': {
      id: '/api/public/hooks/sync-all'
      path: '/api/public/hooks/sync-all'
      fullPath: '/api/public/hooks/sync-all'
      preLoaderRoute: typeof ApiPublicHooksSyncAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pro/entries/$id': {
      id: '/api/public/pro/entries/$id'
      path: '/$id'
      fullPath: '/api/public/pro/entries/$id'
      preLoaderRoute: typeof ApiPublicProEntriesIdRouteImport
      parentRoute: typeof ApiPublicProEntriesRoute
    }
    '/api/public/pi/transaction/$hash': {
      id: '/api/public/pi/transaction/$hash'
      path: '/api/public/pi/transaction/$hash'
      fullPath: '/api/public/pi/transaction/$hash'
      preLoaderRoute: typeof ApiPublicPiTransactionHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/operation/$key': {
      id: '/api/public/pi/operation/$key'
      path: '/api/public/pi/operation/$key'
      fullPath: '/api/public/pi/operation/$key'
      preLoaderRoute: typeof ApiPublicPiOperationKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nft/$slug/cover': {
      id: '/api/public/nft/$slug/cover'
      path: '/cover'
      fullPath: '/api/public/nft/$slug/cover'
      preLoaderRoute: typeof ApiPublicNftSlugCoverRouteImport
      parentRoute: typeof ApiPublicNftSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicNftSlugRouteChildren {
  ApiPublicNftSlugCoverRoute: typeof ApiPublicNftSlugCoverRoute
}

const ApiPublicNftSlugRouteChildren: ApiPublicNftSlugRouteChildren = {
  ApiPublicNftSlugCoverRoute: ApiPublicNftSlugCoverRoute,
}

const ApiPublicNftSlugRouteWithChildren =
  ApiPublicNftSlugRoute._addFileChildren(ApiPublicNftSlugRouteChildren)

interface ApiPublicProEntriesRouteChildren {
  ApiPublicProEntriesIdRoute: typeof ApiPublicProEntriesIdRoute
}

const ApiPublicProEntriesRouteChildren: ApiPublicProEntriesRouteChildren = {
  ApiPublicProEntriesIdRoute: ApiPublicProEntriesIdRoute,
}

const ApiPublicProEntriesRouteWithChildren =
  ApiPublicProEntriesRoute._addFileChildren(ApiPublicProEntriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ExplorerRoute: ExplorerRoute,
  KycRoute: KycRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StableRoute: StableRoute,
  StakeRoute: StakeRoute,
  MerchantsIdRoute: MerchantsIdRoute,
  NftSlugRoute: NftSlugRoute,
  TokensSymbolRoute: TokensSymbolRoute,
  TxHashRoute: TxHashRoute,
  WalletAddressRoute: WalletAddressRoute,
  MerchantsIndexRoute: MerchantsIndexRoute,
  NftIndexRoute: NftIndexRoute,
  PiIndexRoute: PiIndexRoute,
  ProIndexRoute: ProIndexRoute,
  TokensIndexRoute: TokensIndexRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
  ApiPublicTransactionsRoute: ApiPublicTransactionsRoute,
  PiOpKeyRoute: PiOpKeyRoute,
  PiTxHashRoute: PiTxHashRoute,
  ProEntryIdRoute: ProEntryIdRoute,
  ApiPublicHooksSyncAllRoute: ApiPublicHooksSyncAllRoute,
  ApiPublicLedgerBulkRoute: ApiPublicLedgerBulkRoute,
  ApiPublicLedgerRecordRoute: ApiPublicLedgerRecordRoute,
  ApiPublicMerchantIdRoute: ApiPublicMerchantIdRoute,
  ApiPublicNftMarketActivityRoute: ApiPublicNftMarketActivityRoute,
  ApiPublicNftMarketCollectionsRoute: ApiPublicNftMarketCollectionsRoute,
  ApiPublicNftMarketListingsRoute: ApiPublicNftMarketListingsRoute,
  ApiPublicNftMarketStatsRoute: ApiPublicNftMarketStatsRoute,
  ApiPublicNftSlugRoute: ApiPublicNftSlugRouteWithChildren,
  ApiPublicPiAccountRoute: ApiPublicPiAccountRoute,
  ApiPublicPiOperationsRoute: ApiPublicPiOperationsRoute,
  ApiPublicPiPaymentsRoute: ApiPublicPiPaymentsRoute,
  ApiPublicPiTransactionsRoute: ApiPublicPiTransactionsRoute,
  ApiPublicProEntriesRoute: ApiPublicProEntriesRouteWithChildren,
  ApiPublicProStatsRoute: ApiPublicProStatsRoute,
  ApiPublicTokenSymbolRoute: ApiPublicTokenSymbolRoute,
  ApiPublicTransactionHashRoute: ApiPublicTransactionHashRoute,
  ApiPublicWalletAddressRoute: ApiPublicWalletAddressRoute,
  ApiPublicPiOperationKeyRoute: ApiPublicPiOperationKeyRoute,
  ApiPublicPiTransactionHashRoute: ApiPublicPiTransactionHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
